#!/bin/bash
> '/home/tomasz/ML_Research/splendor/gym-splendor/run_script.py'
DATA=$1
first='/'
second='.py'
third=''
DATA2=${DATA//$first/.}
DATA3=${DATA2//$second/$third}
echo 'from' ${DATA3//$first/.} import run_experiment >> '/home/tomasz/ML_Research/splendor/gym-splendor/run_script.py'
echo 'run_experiment()' >> '/home/tomasz/ML_Research/splendor/gym-splendor/run_script.py'
MY_DIR=$2
> '/home/tomasz/ML_Research/splendor/gym-splendor/start_experiment'
echo 'cd gym-splendor' >> '/home/tomasz/ML_Research/splendor/gym-splendor/start_experiment'
echo 'sbatch '$MY_DIR'/run.sbatch' >> '/home/tomasz/ML_Research/splendor/gym-splendor/start_experiment'

rsync -avz --exclude 'renders' --exclude 'archive' /home/tomasz/ML_Research/splendor/gym-splendor plgtodrzygozdz@pro.cyfronet.pl:/net/people/plgtodrzygozdz/
ssh plgtodrzygozdz@pro.cyfronet.pl -o LogLevel=error source gym-splendor/start_experiment
ssh plgtodrzygozdz@pro.cyfronet.pl -o LogLevel=error squeue -u plgtodrzygozdz