#!/bin/bash
> '/home/tomasz/ML_Research/splendor/gym-splendor/run_script.py'
DATA=$1
MY_DIR=$2
first='/'
second='.py'
third=''
DATA2=${DATA//$first/.}
DATA3=${DATA2//$second/$third}

typeset -i num=$(cat '/home/tomasz/ML_Research/splendor/gym-splendor/gym_splendor_code/cluster_utils/batch_files/batch_num')
new_num=$((num+1))

cp -- $DATA  '/home/tomasz/ML_Research/splendor/gym-splendor/gym_splendor_code/cluster_utils/run_files/run_'$num'.py'


> '/home/tomasz/ML_Research/splendor/gym-splendor/run_script.py'
echo 'from gym_splendor_code.cluster_utils.run_files.run_'$num 'import run_experiment' >> '/home/tomasz/ML_Research/splendor/gym-splendor/run_script.py'
echo 'run_experiment()' >> '/home/tomasz/ML_Research/splendor/gym-splendor/run_script.py'

> '/home/tomasz/ML_Research/splendor/gym-splendor/start_experiment'
echo 'cd gym-splendor' >> '/home/tomasz/ML_Research/splendor/gym-splendor/start_experiment'


 > '/home/tomasz/ML_Research/splendor/gym-splendor/gym_splendor_code/cluster_utils/batch_files/batch_num'
echo $new_num >> '/home/tomasz/ML_Research/splendor/gym-splendor/gym_splendor_code/cluster_utils/batch_files/batch_num'

cp -- $MY_DIR'/run.sbatch'  '/home/tomasz/ML_Research/splendor/gym-splendor/gym_splendor_code/cluster_utils/batch_files/run_'$num'.sbatch'
echo 'sbatch gym_splendor_code/cluster_utils/batch_files/run_'$num'.sbatch' >> '/home/tomasz/ML_Research/splendor/gym-splendor/start_experiment'

rsync -avz --exclude 'renders' --exclude 'archive' /home/tomasz/ML_Research/splendor/gym-splendor plgtodrzygozdz@pro.cyfronet.pl:/net/people/plgtodrzygozdz/
ssh plgtodrzygozdz@pro.cyfronet.pl -o LogLevel=error source gym-splendor/start_experiment
ssh plgtodrzygozdz@pro.cyfronet.pl -o LogLevel=error squeue -u plgtodrzygozdz